runtime: python311
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"
  DB_USERNAME: "root"
  DB_PASSWORD: "123456"
  DB_HOST: "35.198.30.135"
  DB_NAME: "sistema"

handlers:
- url: /.*
  script: auto
